
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'dsshuttle' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for dsshuttle

  pod 'Firebase/Messaging', '~> 6.3.0'

end